### ISSUE TITLE
Delay-Tolerant-Network code is working on ns3.30

### ISSUE THREAD

**Issue by webdebugg** [nbolar/Delay-Tolerant-Network#1]
when i run your code on ns3.30 it shows this error.

Waf: Entering directory `/home/bilalsafdar/ns-allinone-3.30/ns-3.30/build'
[2738/2788] Compiling scratch/code.cc
../scratch/code.cc: In function ‘int main(int, char**)’:
../scratch/code.cc:462:9: error: ‘NqosWifiMacHelper’ was not declared in this scope
  462 |         NqosWifiMacHelper wifiMac = NqosWifiMacHelper::Default ();
      |         ^~~~~~~~~~~~~~~~~
../scratch/code.cc:466:9: error: ‘wifiMac’ was not declared in this scope
  466 |         wifiMac.SetType ("ns3::AdhocWifiMac"); //Set MAC to ad hoc mode
      |         ^~~~~~~

Waf: Leaving directory `/home/bilalsafdar/ns-allinone-3.30/ns-3.30/build'
Build failed
 -> task in 'code' failed with exit status 1 (run with -v to display more information)
